Movie.create(title: "Sleepless in Seattle", directed_by: "Nora Ephron", rank: 56, description: "Best love story of all time")
Movie.create(title: "Star Wars", directed_by: "George Lucas", rank: 99, description: "Use the Force, Luke")
Movie.create(title: "The Hunger Games", directed_by: "Gary Ross", rank: 80, description: "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.")

Album.create(title: "To Be Everywhere Is To Be Nowhere", recorded_by: "Thrice", rank: 93, description: "Oh, we say we'll do it when things settle down, we say we'll do it when this season's through. We say we'll do it when we get around to it. But it's already overdue.")
Album.create(title: "I Am The Movie", recorded_by: "Motion City Soundtrack", rank: 32, description: "Someday I fear I will be rescued from the boredom line.")
Album.create(title: "Every Open Eye", recorded_by: "CHVRCHES", rank: 61, description: "We tried to bury it and rise above, bury it and rise above")

Book.create(title: "Women in Tech", written_by: "Tara Wheeler Van Vlack", rank: 78, description: "Geared toward women who are considering getting into tech, or those already in a tech job who want to take their career to the next level, this book combines practical career advice and inspiring personal stories from successful female tech professionals.")
Book.create(title: "All the Single Ladies: Unmarried Women and the Rise of an Independent Nation", written_by: "Rebecca Traister", rank: 87, description: "Today, only twenty percent of Americans are wed by age twenty-nine, compared to nearly sixty percent in 1960. The Population Reference Bureau calls it a “dramatic reversal.” All the Single Ladies is a remarkable portrait of contemporary American life and how we got here, through the lens of the single American woman. Covering class, race, sexual orientation, and filled with vivid anecdotes from fascinating contemporary and historical figures, All the Single Ladies is destined to be a classic work of social history and journalism.")
Book.create(title: "She's Such a Geek: Women Write About Science, Technology, and Other Nerdy Stuff", written_by: "Annalee Newitz", rank: 78, description: "A groundbreaking anthology that celebrates women who have flourished in the male-dominated realms of technical and cultural arcana.")
